/* vibrotato - small, dependency-free WebGL2 instancing renderer. */
'use strict';
const V3={
 add:(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub:(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],
 mul:(a,k)=>[a[0]*k,a[1]*k,a[2]*k],dot:(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],
 cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],
 norm:a=>{let d=Math.hypot(...a)||1;return a.map(v=>v/d)}
};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),mix=(a,b,t)=>a+(b-a)*t,rand=(a=0,b=1)=>a+Math.random()*(b-a),TAU=Math.PI*2;
function hex(c){if(Array.isArray(c))return c;return [(c>>16&255)/255,(c>>8&255)/255,(c&255)/255]}
function perspective(fov,aspect,n,f){let t=1/Math.tan(fov/2);return new Float32Array([t/aspect,0,0,0,0,t,0,0,0,0,(f+n)/(n-f),-1,0,0,2*f*n/(n-f),0])}
function lookAt(eye,target){let z=V3.norm(V3.sub(eye,target)),x=V3.norm(V3.cross([0,1,0],z)),y=V3.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V3.dot(x,eye),-V3.dot(y,eye),-V3.dot(z,eye),1])}
function matMul(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function composeInto(d,i,x,y,z,sx,sy,sz,rx,ry,rz){let a=Math.cos(rx),b=Math.sin(rx),c=Math.cos(ry),s=Math.sin(ry),e=Math.cos(rz),f=Math.sin(rz);d[i]=c*e*sx;d[i+1]=(a*f+b*s*e)*sx;d[i+2]=(b*f-a*s*e)*sx;d[i+3]=0;d[i+4]=-c*f*sy;d[i+5]=(a*e-b*s*f)*sy;d[i+6]=(b*e+a*s*f)*sy;d[i+7]=0;d[i+8]=s*sz;d[i+9]=-b*c*sz;d[i+10]=a*c*sz;d[i+11]=0;d[i+12]=x;d[i+13]=y;d[i+14]=z;d[i+15]=1}
function makeGeometry(type){let p=[],n=[];function tri(a,b,c,na,nb=na,nc=na){p.push(...a,...b,...c);n.push(...na,...nb,...nc)}
 if(type==='box'){
 let faces=[[[1,0,0],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]],[[-1,0,0],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]],[[0,1,0],[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]],[[0,-1,0],[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]],[[0,0,1],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]],[[0,0,-1],[.5,-.5,-.5],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5]]];for(let [nm,a,b,c,d] of faces){tri(a,b,c,nm);tri(a,c,d,nm)}
 }else if(type==='sphere'||type==='octa'){
 let seg=type==='sphere'?12:4,rings=type==='sphere'?8:2;
 function v(i,j){let ph=Math.PI*i/rings,th=TAU*j/seg;return [Math.sin(ph)*Math.cos(th),Math.cos(ph),Math.sin(ph)*Math.sin(th)]}
 for(let i=0;i<rings;i++)for(let j=0;j<seg;j++){let a=v(i,j),b=v(i+1,j),c=v(i+1,j+1),d=v(i,j+1);tri(a,b,c,a,b,c);tri(a,c,d,a,c,d)}
 }else if(type==='cylinder'||type==='cone'){
 let seg=12,top=type==='cone'?0:1;for(let i=0;i<seg;i++){let t=TAU*i/seg,u=TAU*(i+1)/seg,a=[Math.cos(t),-.5,Math.sin(t)],b=[Math.cos(u),-.5,Math.sin(u)],c=[top*Math.cos(u),.5,top*Math.sin(u)],d=[top*Math.cos(t),.5,top*Math.sin(t)],na=[Math.cos(t),top?0:.7,Math.sin(t)],nb=[Math.cos(u),top?0:.7,Math.sin(u)];tri(a,b,c,na,nb,nb);tri(a,c,d,na,nb,na);tri([0,.5,0],d,c,[0,1,0]);tri([0,-.5,0],b,a,[0,-1,0])}
 }else if(type==='ring'){
 let seg=64;for(let i=0;i<seg;i++){let t=TAU*i/seg,u=TAU*(i+1)/seg,a=[Math.cos(t),0,Math.sin(t)],b=[Math.cos(u),0,Math.sin(u)],c=[.97*Math.cos(u),0,.97*Math.sin(u)],d=[.97*Math.cos(t),0,.97*Math.sin(t)];tri(a,b,c,[0,1,0]);tri(a,c,d,[0,1,0])}
 }
 return {p:new Float32Array(p),n:new Float32Array(n)};
}
class VibrotatoRenderer{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:false,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true});if(!this.gl)throw Error('WebGL2 is unavailable. Please enable browser hardware acceleration.');let gl=this.gl;
 const vs=`#version 300 es
 precision highp float;layout(location=0) in vec3 position;layout(location=1) in vec3 normal;layout(location=2) in mat4 model;layout(location=6) in vec4 color;layout(location=7) in vec4 properties;uniform mat4 vp;out vec3 vNormal;out vec3 vWorld;out vec4 vColor;out vec4 vProps;void main(){vec4 w=model*vec4(position,1.);vWorld=w.xyz;vNormal=normalize(mat3(model)*normal);vColor=color;vProps=properties;gl_Position=vp*w;}`;
 const fs=`#version 300 es
 precision highp float;in vec3 vNormal;in vec3 vWorld;in vec4 vColor;in vec4 vProps;uniform vec3 eye;uniform vec3 player;uniform float time;out vec4 frag;void main(){vec3 n=normalize(vNormal);vec3 l=normalize(vec3(-.5,1.,.4));float diffuse=max(dot(n,l),0.);float hemi=.24+.17*max(n.y,0.);vec3 base=vColor.rgb;vec3 c=base*(hemi+diffuse*.75);vec3 v=normalize(eye-vWorld);float spec=pow(max(dot(reflect(-l,n),v),0.),30.)*.22;c+=vec3(.28,.6,.75)*spec;float d=length(vWorld.xz-player.xz);c+=base*vec3(.12,.65,.62)*max(0.,1.-d/8.)*.48;float rim=pow(1.-max(dot(n,v),0.),3.)*.13;c+=vec3(.13,.55,.65)*rim;float emission=vProps.x;c=mix(c,base,clamp(emission,0.,1.))+base*max(0.,emission-1.)*.35;
 if(vProps.z>.5){vec2 coord=vWorld.xz;vec2 g=abs(fract(coord/2.-.5)-.5)/max(fwidth(coord/2.),vec2(.001));float line=1.-min(min(g.x,g.y),1.);float checker=mod(floor(coord.x/2.)+floor(coord.y/2.),2.);c=vec3(.021,.043,.065)+checker*.008;c+=vec3(.035,.105,.13)*line*.43;float lane=step(abs(coord.x),.045)+step(abs(coord.y),.045);c+=vec3(.11,.28,.25)*lane;float pulse=exp(-abs(length(coord)-mod(time*3.,32.))*2.);c+=vec3(.0,.06,.07)*pulse;float light=max(0.,1.-d/5.);c+=vec3(.006,.068,.056)*light;}
 float fog=1.-exp(-length(eye-vWorld)*.0035);c=mix(c,vec3(.016,.025,.054),fog);frag=vec4(c,vColor.a);}`;
 this.program=this.programFrom(vs,fs);this.loc={};for(let x of ['vp','eye','player','time'])this.loc[x]=gl.getUniformLocation(this.program,x);
 const qvs=`#version 300 es
 precision highp float;out vec2 uv;void main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));uv=p;gl_Position=vec4(p*2.-1.,0.,1.);}`;
 const qfs=`#version 300 es
 precision highp float;in vec2 uv;uniform sampler2D image;uniform sampler2D glow;uniform vec2 resolution;uniform float bloom;uniform float time;uniform float hurt;out vec4 frag;void main(){vec3 c=texture(image,uv).rgb+texture(glow,uv).rgb*bloom;float vignette=smoothstep(.2,.83,length((uv-.5)*vec2(1.,.83)));c*=1.-vignette*.42;c+=vec3(.8,.025,.06)*hurt*vignette*.5;float noise=fract(sin(dot(uv*resolution+time,vec2(12.9898,78.233)))*43758.5453);c+=(noise-.5)*.005;c=pow(max(c,vec3(0.)),vec3(.90));frag=vec4(c,1.);}`;
 this.post=this.programFrom(qvs,qfs);this.postLoc={};for(let x of ['image','glow','resolution','bloom','time','hurt'])this.postLoc[x]=gl.getUniformLocation(this.post,x);
 const bfs=`#version 300 es
 precision highp float;in vec2 uv;uniform sampler2D image;uniform vec2 direction;uniform float prefilter;out vec4 frag;vec3 sampleAt(vec2 p){vec3 c=texture(image,p).rgb;if(prefilter>.5)c*=max(0.,max(max(c.r,c.g),c.b)-.55)*1.6;return c;}void main(){vec3 c=sampleAt(uv)*.227027;c+=(sampleAt(uv+direction*1.384615)+sampleAt(uv-direction*1.384615))*.316216;c+=(sampleAt(uv+direction*3.230769)+sampleAt(uv-direction*3.230769))*.070270;frag=vec4(c,1.);}`;
 this.blur=this.programFrom(qvs,bfs);this.blurLoc={};for(let x of ['image','direction','prefilter'])this.blurLoc[x]=gl.getUniformLocation(this.blur,x);
 this.glows=Array.from({length:2},()=>({fb:gl.createFramebuffer(),tex:gl.createTexture()}));
 this.shapes={};this.maxInstances=12000;
 for(let type of ['box','sphere','octa','cylinder','cone','ring']){let geo=makeGeometry(type),vao=gl.createVertexArray();gl.bindVertexArray(vao);for(let [loc,data]of [[0,geo.p],[1,geo.n]]){let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0)}let buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,this.maxInstances*24*4,gl.DYNAMIC_DRAW);for(let i=0;i<6;i++){let loc=i+2;gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,4,gl.FLOAT,false,96,i*16);gl.vertexAttribDivisor(loc,1)}this.shapes[type]={vao,buffer,count:geo.p.length/3,instances:0,data:new Float32Array(this.maxInstances*24)};}
 gl.bindVertexArray(null);this.postVAO=gl.createVertexArray();this.fb=gl.createFramebuffer();this.tex=gl.createTexture();this.depth=gl.createRenderbuffer();this.width=0;this.height=0;this.quality=1.25;this.bloom=1.65;this.fov=.72;this.eye=[27,38,35];this.target=[0,0,0];this.drawCalls=0;
 }
 programFrom(v,f){let gl=this.gl,p=gl.createProgram();for(let [t,s]of [[gl.VERTEX_SHADER,v],[gl.FRAGMENT_SHADER,f]]){let sh=gl.createShader(t);gl.shaderSource(sh,s);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));gl.attachShader(p,sh)}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
 resize(){let gl=this.gl,w=Math.floor(innerWidth*Math.min(devicePixelRatio||1,this.quality)),h=Math.floor(innerHeight*Math.min(devicePixelRatio||1,this.quality));if(w===this.width&&h===this.height)return;this.width=this.canvas.width=w;this.height=this.canvas.height=h;gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindRenderbuffer(gl.RENDERBUFFER,this.depth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT24,w,h);gl.bindFramebuffer(gl.FRAMEBUFFER,this.fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.tex,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,this.depth);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Framebuffer allocation failed');this.bloomW=Math.max(1,Math.ceil(w/4));this.bloomH=Math.max(1,Math.ceil(h/4));for(let target of this.glows){gl.bindTexture(gl.TEXTURE_2D,target.tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,this.bloomW,this.bloomH,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindFramebuffer(gl.FRAMEBUFFER,target.fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,target.tex,0)}gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
 begin(){this.resize();for(let s of Object.values(this.shapes))s.instances=0;this.vp=matMul(perspective(this.fov,this.width/this.height,.2,220),lookAt(this.eye,this.target))}
 mesh(type,x,y,z,sx,sy,sz,color,emission=0,rx=0,ry=0,rz=0,ground=0){let s=this.shapes[type];if(s.instances>=this.maxInstances)return;let i=s.instances++*24,d=s.data;composeInto(d,i,x,y,z,sx,sy,sz,rx,ry,rz);let c=hex(color);d[i+16]=c[0];d[i+17]=c[1];d[i+18]=c[2];d[i+19]=1;d[i+20]=emission;d[i+21]=0;d[i+22]=ground;d[i+23]=0}
 line(ax,ay,az,bx,by,bz,width,color,emission=1){let dx=bx-ax,dy=by-ay,dz=bz-az,len=Math.hypot(dx,dy,dz)||.01;let yaw=Math.atan2(dx,dz),pitch=-Math.atan2(dy,Math.hypot(dx,dz));this.mesh('box',(ax+bx)/2,(ay+by)/2,(az+bz)/2,width,width,len,color,emission,pitch,yaw,0)}
 project(x,y,z){let m=this.vp,cx=m[0]*x+m[4]*y+m[8]*z+m[12],cy=m[1]*x+m[5]*y+m[9]*z+m[13],w=m[3]*x+m[7]*y+m[11]*z+m[15];return [(cx/w*.5+.5)*innerWidth,(-cy/w*.5+.5)*innerHeight,w]}
 groundPoint(mx,my){let f=V3.norm(V3.sub(this.target,this.eye)),r=V3.norm(V3.cross(f,[0,1,0])),u=V3.cross(r,f),t=Math.tan(this.fov/2),nx=mx/innerWidth*2-1,ny=1-my/innerHeight*2;let d=V3.add(f,V3.add(V3.mul(r,nx*t*this.width/this.height),V3.mul(u,ny*t)));let k=(.8-this.eye[1])/d[1];return [this.eye[0]+d[0]*k,this.eye[2]+d[2]*k]}
 render(time,player,hurt=0){let gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,this.fb);gl.viewport(0,0,this.width,this.height);gl.clearColor(.016,.025,.054,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.disable(gl.BLEND);gl.useProgram(this.program);gl.uniformMatrix4fv(this.loc.vp,false,this.vp);gl.uniform3fv(this.loc.eye,this.eye);gl.uniform3fv(this.loc.player,[player.x,.8,player.z]);gl.uniform1f(this.loc.time,time);this.drawCalls=0;for(let s of Object.values(this.shapes)){if(!s.instances)continue;gl.bindVertexArray(s.vao);gl.bindBuffer(gl.ARRAY_BUFFER,s.buffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,s.data.subarray(0,s.instances*24));gl.drawArraysInstanced(gl.TRIANGLES,0,s.count,s.instances);this.drawCalls++}gl.disable(gl.DEPTH_TEST);gl.bindVertexArray(this.postVAO);gl.useProgram(this.blur);gl.viewport(0,0,this.bloomW,this.bloomH);gl.uniform1i(this.blurLoc.image,0);for(let i=0;i<2;i++){gl.bindFramebuffer(gl.FRAMEBUFFER,this.glows[i].fb);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,i===0?this.tex:this.glows[0].tex);gl.uniform2f(this.blurLoc.direction,i===0?1/this.bloomW:0,i===1?1/this.bloomH:0);gl.uniform1f(this.blurLoc.prefilter,i===0?1:0);gl.drawArrays(gl.TRIANGLES,0,3);this.drawCalls++}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.width,this.height);gl.useProgram(this.post);gl.bindVertexArray(this.postVAO);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.uniform1i(this.postLoc.image,0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.glows[1].tex);gl.uniform1i(this.postLoc.glow,1);gl.uniform2f(this.postLoc.resolution,this.width,this.height);gl.uniform1f(this.postLoc.bloom,this.bloom);gl.uniform1f(this.postLoc.time,time);gl.uniform1f(this.postLoc.hurt,hurt);gl.drawArrays(gl.TRIANGLES,0,3);this.drawCalls++}
}
window.VibrotatoRenderer=VibrotatoRenderer;
